#!/usr/bin/env python3
import sys
sys.path.append("..")

from gui.application import Application

import logging
from Constants import LOG_CONFIG

logging.basicConfig(**LOG_CONFIG)
log: logging = logging.getLogger(__name__)


if __name__ == "__main__":
    app = Application()
    app.run(sys.argv)
